//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string Btn_Canceled {
            get {
                return ResourceManager.GetString("Btn_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string Btn_Saved {
            get {
                return ResourceManager.GetString("Btn_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Btn_saves {
            get {
                return ResourceManager.GetString("Btn_saves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Btn_Submit {
            get {
                return ResourceManager.GetString("Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITHI MASTER.
        /// </summary>
        internal static string headTithi {
            get {
                return ResourceManager.GetString("headTithi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHADAVA MASTER.
        /// </summary>
        internal static string Head_Chadhava {
            get {
                return ResourceManager.GetString("Head_Chadhava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Master.
        /// </summary>
        internal static string Head_Transaction {
            get {
                return ResourceManager.GetString("Head_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chadava Name.
        /// </summary>
        internal static string lblChadhava {
            get {
                return ResourceManager.GetString("lblChadhava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chadava Master.
        /// </summary>
        internal static string lblChadhavamaster {
            get {
                return ResourceManager.GetString("lblChadhavamaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string lblDashboard {
            get {
                return ResourceManager.GetString("lblDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration.
        /// </summary>
        internal static string lbleIteration {
            get {
                return ResourceManager.GetString("lbleIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration Master.
        /// </summary>
        internal static string lblIterationmaster {
            get {
                return ResourceManager.GetString("lblIterationmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Language Master.
        /// </summary>
        internal static string lblLang {
            get {
                return ResourceManager.GetString("lblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Master.
        /// </summary>
        internal static string lbllanguagemaster {
            get {
                return ResourceManager.GetString("lbllanguagemaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAIN MANDIR.
        /// </summary>
        internal static string lblMandir {
            get {
                return ResourceManager.GetString("lblMandir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string lblmaster {
            get {
                return ResourceManager.GetString("lblmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string lblReportsmaster {
            get {
                return ResourceManager.GetString("lblReportsmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tithi Master.
        /// </summary>
        internal static string lblTithimaster {
            get {
                return ResourceManager.GetString("lblTithimaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string lblTransactionmaster {
            get {
                return ResourceManager.GetString("lblTransactionmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.E.F Date.
        /// </summary>
        internal static string lblWEF_Date {
            get {
                return ResourceManager.GetString("lblWEF_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lbl_Amount {
            get {
                return ResourceManager.GetString("lbl_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chadhava Name.
        /// </summary>
        internal static string lbl_Chadhava {
            get {
                return ResourceManager.GetString("lbl_Chadhava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor Name.
        /// </summary>
        internal static string lbl_DonorName {
            get {
                return ResourceManager.GetString("lbl_DonorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string lbl_Image {
            get {
                return ResourceManager.GetString("lbl_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration.
        /// </summary>
        internal static string lbl_Iteration {
            get {
                return ResourceManager.GetString("lbl_Iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        internal static string lbl_SelectDate {
            get {
                return ResourceManager.GetString("lbl_SelectDate", resourceCulture);
            }
        }
    }
}
